namespace: derekwaters
name: rh_errata
version: 1.0.0
readme: README.md
authors:
  - Derek Waters <derek@frisbeeworld.com>
description: Trigger EDA events when new Red Hat errata are published
license:
  - GPL-2.0-or-later
tags:
  - eda
  - errata
  - rhsa
  - cve
dependencies: {}
repository: https://github.com/derekwaters/rh_errata
documentation: https://github.com/derekwaters/rh_errata/README.md
homepage: https://github.com/derekwaters/rh_errata/
issues: https://github.com/derekwaters/rh_errata/issues
build_ignore: []
